# Generated by Django 2.0.6 on 2018-06-18 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Publicated'),
        ),
        migrations.AddField(
            model_name='article',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(blank=True, help_text="Don't change the field manually!", max_length=150, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, help_text="Don't change the field manually!", max_length=150, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vlog.Article', verbose_name='Article'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(db_table='tag__article', related_name='tags', to='vlog.Article', verbose_name='Articles'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(blank=True, help_text="Don't change the field manually!", max_length=150, unique=True, verbose_name='Slug'),
        ),
    ]
